### PR TITLE
Use nvcomp:: namespace in target_link_libraries.  Resolves #83.

### LINKED ISSUE #83: [BUG] nvcomp namespace required in target_link_libraries (CMake 2.23.2)
**Describe the bug**
An "nvcomp::" namespace seems to be required in target_link_libraries with newer versions of CMake (I'm using 2.23.2 under Linux).  Otherwise the include path doesn't include nvcomp/include:
low_level_quickstart_example.cpp:5:10: fatal error: nvcomp/lz4.h: No such file or directory

**Steps/Code to reproduce bug**
Build with CMake 2.23.2 under Linux

**Additional context**
I will submit a pull request with a fix.

### PR DESCRIPTION
**Pull request by MarkLeone**

### CODE REVIEW

**Review by eschmidt-nvidia — APPROVED** [review]
Looks good, thanks.
