### ISSUE TITLE
[BUG] nvcomp namespace required in target_link_libraries (CMake 2.23.2)

### ISSUE THREAD

**Issue by MarkLeone** [NVIDIA/nvcomp#83]
**Describe the bug**
An "nvcomp::" namespace seems to be required in target_link_libraries with newer versions of CMake (I'm using 2.23.2 under Linux).  Otherwise the include path doesn't include nvcomp/include:
low_level_quickstart_example.cpp:5:10: fatal error: nvcomp/lz4.h: No such file or directory

**Steps/Code to reproduce bug**
Build with CMake 2.23.2 under Linux

**Additional context**
I will submit a pull request with a fix.

**Comment by eschmidt-nvidia** [comment]
Hi Mark. Thanks for the report / PR. I'll approve it. 

FYI, I think the issue isn't with cmake version but rather in our local testing nvcomp is installed in a location that was otherwise added to the include path.
